config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', controller: 'home', action: 'index'

  get '/concerts', controller: 'concert', action: 'index', as: 'concert_index'
  get '/concerts/:slug', controller: 'concert', action: 'show', as: 'concert_show'
  get '/future-concerts', controller: 'concert', action: 'future_concerts', as: 'future_concerts_index'
  get '/archive-concerts', controller: 'concert', action: 'archive_concerts', as: 'archive_concerts_index'

  get '/news', controller: 'news', action: 'index', as: 'news_index'
  get '/news/:slug', controller: 'news', action: 'show', as: 'news'

  get '/articles', controller: 'article', action: 'index', as: 'article_index'
  get '/articles/:slug', controller: 'article', action: 'show', as: 'article_show'

  get '/bands', controller: 'band', action: 'index', as: 'band_index'
  get '/bands/:slug', controller: 'band', action: 'show', as: 'band_show'

  get '/bases', controller: 'base', action: 'index', as: 'base_index'
  get '/bases/:slug', controller: 'base', action: 'show', as: 'base_show'

  get '/gallery', controller: 'photo_album', action: 'index', as: 'gallery_index'
  get '/gallery/:slug', controller: 'photo_album', action: 'show', as: 'gallery_show'

  get '/videos', controller: 'video', action: 'index', as: 'video_index'
  get '/videos/:slug', controller: 'video', action: 'show', as: 'video_show'

  post '/subscribers', to: 'subscriber#create', as: 'create_subscriber'
end

app/models/concert.rb
# == Schema Information
#
# Table name: concerts
#
#  id           :integer          not null, primary key
#  name         :string
#  slug         :string
#  date_start   :datetime
#  place        :string
#  ticket_price :integer
#  poster_image :string
#  description  :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  show         :boolean          default(TRUE)
#

class Concert < ApplicationRecord
  extend FriendlyId
  include Unisender

  after_create :delayed_send_message

  self.table_name = 'concerts'

  validates :name, :date_start, :place, :poster_image, :ticket_price, presence: true
  friendly_id :name, use: :slugged

  has_many :concert_to_bands, inverse_of: :concert, dependent: :destroy
  has_many :bands, through: :concert_to_bands
  has_one :photo_album

  mount_uploader :poster_image, ConcertUploader

  private
  def delayed_send_message
    NewsLetterSenderWorker.perform_async(self.class.name, self.id)
  end

  def self.create_newsletter(id)
    concert = Concert.find(id)
    # слать анонс если дата концерта больше текущей
    if concert.date_start > Time.now
      ac = ActionController::Base.new
      message_body = ac.render_to_string template: 'concert/mail', layout: false, locals: { concert: concert }
      Unisender.create_email_message concert.name, message_body
    end
  end

end

app/controllers/concert_controller.rb
class ConcertController < ApplicationController
  include ViewHelper

  def index
    @concerts = get_future_concerts(5)
    @archive_concerts = get_archive_concerts(4)
  end

  def show
    @concert = Concert.find_by_slug(params[:slug])
  end

  def future_concerts
    @future_concerts = Kaminari.paginate_array(get_future_concerts).page(params[:page]).per(8)
  end

  def archive_concerts
    @archive_concerts = Kaminari.paginate_array(get_archive_concerts).page(params[:page]).per(8)
  end

  private
  def get_future_concerts(first_count=nil)
    if first_count.nil?
      Concert.where('date_start >= now()').includes(:bands).order(:date_start)
    else
      Concert.where('date_start >= now()').includes(:bands).order(:date_start).first(first_count)
    end
  end

  def get_archive_concerts(first_count=nil)
    if first_count.nil?
      Concert.where('date_start < now()').includes(:bands).order(:date_start)
    else
      Concert.where('date_start < now()').includes(:bands).order(:date_start).first(4)
    end
  end

end

app/helpers/concert_helper.rb
module ConcertHelper
end

app/views/concert/_archive_concerts.html.slim
.concerts id="future-concerts"
  .row
    .col-xs-12
      h1.block-title
        = link_to "Архив концертов", archive_concerts_index_path

  .poster-wrapper-mobile
    - @archive_concerts.each do |concert|
      .row
        .poster-mobile-content
          .col-xs-6
            = link_to concert_show_path(concert.slug), class: 'js-popup-link'
              = image_tag concert.poster_image.url
          .col-xs-6
            .poster-mobile-info-content
              .poster-mobile-title #{concert.name}
              .poster-mobile-text #{concert.place}
              .poster-mobile-date #{l concert.date_start.to_date} #{concert.date_start.hour}:#{concert.date_start.min.to_s.rjust(2, '0')}
              - concert.bands.each do |band|
                .poster-mobile-band #{band.name}

              .poster-mobile-price Вход: #{concert.ticket_price}р.

  .posters-container
    .row
      - @archive_concerts.each do |concert|
        .col-md-3.poster-block
          = link_to concert_show_path(concert.slug), class: 'js-popup-link'
            = image_tag concert.poster_image.url, class: "poster"
            .poster-info
              .title #{concert.name}
              .place #{concert.place}
              .date #{l concert.date_start.to_date} #{concert.date_start.hour}:#{concert.date_start.min.to_s.rjust(2, '0')}
              - concert.bands.each do |band|
                .band #{band.name}

              .payment Вход: #{concert.ticket_price}р.

app/views/concert/_archive_concerts_block.html.slim
.poster-wrapper-mobile
  = render partial: 'concert/concert_mobile', collection: @archive_concerts

.posters-container
  = render partial: 'concert/concert', collection: @archive_concerts
  .clearfix
= render partial: 'pagination/link_to_next_page', locals: {collection: @archive_concerts}

app/views/concert/_concert.html.slim
.col-md-3.poster-block
  = link_to concert_show_path(concert.slug), class: 'js-popup-link'
    = image_tag concert.poster_image.url, class: "poster"
    .poster-info
      .title #{concert.name}
      .place #{concert.place}
      .date #{l concert.date_start.to_date} #{concert.date_start.hour}:#{concert.date_start.min.to_s.rjust(2, '0')}
      - concert.bands.each do |band|
        .band #{band.name}

      .payment Вход: #{concert.ticket_price}р.

app/views/concert/_concert_mobile.html.slim
.row
  .poster-mobile-content
    .col-xs-6
      = link_to concert_show_path(concert_mobile.slug), class: 'js-popup-link'
        = image_tag concert_mobile.poster_image.url
    .col-xs-6
      .poster-mobile-info-content
        .poster-mobile-title #{concert_mobile.name}
        .poster-mobile-text #{concert_mobile.place}
        .poster-mobile-date #{l concert_mobile.date_start.to_date} #{concert_mobile.date_start.hour}:#{concert_mobile.date_start.min.to_s.rjust(2, '0')}
        - concert_mobile.bands.each do |band|
          .poster-mobile-band #{band.name}

        .poster-mobile-price Вход: #{concert_mobile.ticket_price}р.

app/views/concert/_future_concerts.html.slim
.concerts id="future-concerts"
  .row
    .col-xs-12
      h1.block-title
        = link_to "Ожидаются", future_concerts_index_path

  .poster-wrapper-mobile
    - for i in 1..@concerts.count - 1
      - unless @concerts[i].nil?
        .row
          .poster-mobile-content
            .col-xs-6
              = link_to concert_show_path(@concerts[i].slug), class: 'js-popup-link'
                = image_tag @concerts[i].poster_image.url
            .col-xs-6
              .poster-mobile-info-content
                .poster-mobile-title #{@concerts[i].name}
                .poster-mobile-text #{@concerts[i].place}
                .poster-mobile-date #{l @concerts[i].date_start.to_date} #{@concerts[i].date_start.hour}:#{@concerts[i].date_start.min.to_s.rjust(2, '0')}
                - @concerts[i].bands.each do |band|
                  .poster-mobile-band #{band.name}

                .poster-mobile-price Вход: #{@concerts[i].ticket_price}р.

  .posters-container
    .row
      - for i in 1..@concerts.count - 1
        - unless @concerts[i].nil?
          .col-md-3.poster-block
            = link_to concert_show_path(@concerts[i].slug), class: 'js-popup-link'
              = image_tag @concerts[i].poster_image.url, class: "poster"
              .poster-info
                .title #{@concerts[i].name}
                .place #{@concerts[i].place}
                .date #{l @concerts[i].date_start.to_date} #{@concerts[i].date_start.hour}:#{@concerts[i].date_start.min.to_s.rjust(2, '0')}
                - @concerts[i].bands.each do |band|
                  .band #{band.name}

                .payment Вход: #{@concerts[i].ticket_price}р.

app/views/concert/_future_concerts_block.html.slim
.poster-wrapper-mobile
  = render partial: 'concert/concert_mobile', collection: @future_concerts

.posters-container
  = render partial: 'concert/concert', collection: @future_concerts
  .clearfix
= render partial: 'pagination/link_to_next_page', locals: {collection: @future_concerts}

app/views/concert/_last_concert.html.slim
.last-concert-wrapper
  .row
    .col-xs-6.col-md-4.col-md-offset-1
      = link_to concert_show_path(@concerts[0].slug), class: 'js-popup-link'
        = image_tag @concerts[0].poster_image.url, class: "last-concert-image"
    .col-xs-6.col-md-6
      .last-concert-info
        = link_to concert_show_path(@concerts[0].slug), class: 'js-popup-link'
          .title #{@concerts[0].name}
        .place #{@concerts[0].place}
        .date-wrapper
          .date #{l @concerts[0].date_start.to_date}
          .time Начало: #{@concerts[0].date_start.hour}:#{@concerts[0].date_start.min.to_s.rjust(2, '0')}
        .bands
          - @concerts[0].bands.each do |band|
            .anonce-band #{band.name}

        .payment Вход: #{@concerts[0].ticket_price}p.
  .row
    .col-xs-12
      = link_to "Cледующие консерты", future_concerts_index_path, class: 'next-concerts-link'

app/views/concert/archive_concerts.html.slim
.concerts
  .container
    .row
      h1.block-title Архив концертов
    .row
      = render 'concert/archive_concerts_block'

app/views/concert/future_concerts.html.slim
.concerts
  .container
    .row
      h1.block-title Будущие концерты
    .row
      = render 'concert/future_concerts_block'

app/views/concert/index.html.slim
.container
  - if @concerts.count > 0
    = render 'concert/last_concert'
    = render partial: 'concert/future_concerts'
  - if @archive_concerts.count > 0
    = render partial: 'concert/archive_concerts'

app/views/concert/show.html.slim
.concert-detail-wrapper
  .container
    .row
      .col-xs-12.col-sm-10.col-md-offset-1
        .base-detail-page.js-page-container
          .row
            .col-xs-6.col-sm-4
              .base-detail-page__image-block
                = image_tag @concert.poster_image.url
            .col-xs-6.col-sm-8
              .base-detail-page__info-block
                h1.base-info-block__title
                  = @concert.name
                .base-info-block__info-line
                  span
                    | Место:&nbsp;
                  = @concert.place
                .base-info-block__info-line
                  span
                    | Начало:&nbsp;
                  | #{l @concert.date_start.to_date} в #{@concert.date_start.hour}:#{@concert.date_start.min.to_s.rjust(2, '0')}
                .base-info-block__info-line
                  span.span-with-margin-10
                    | Играют:&nbsp;
                  ul
                    - @concert.bands.each do |band|
                      li
                        = band.name
                .base-info-block__info-line
                  span.inline-span
                    | Вход:&nbsp;
                  = "#{@concert.ticket_price} р."
                .base-repost
                  .base-repost__title
                    | Поделиться:
                  .base-repost__links
                    .base-repost__social-button.base-repost__social-button--vk
                      = render 'svg/vk_icon'
                    = link_to "//facebook.com/share.php?u=kemrockfest.ru#{request.fullpath}&title=#{@concert.name}", class: 'base-repost__social-button base-repost__social-button--facebook', target: '_blank'
                      = render 'svg/fb_icon'
            .clearfix
          .row
            .col-sm-10.col-sm-offset-1
              .base-detail-page__text-block
                == @concert.description
            .clearfix
      .clearfix