config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', controller: 'home', action: 'index'

  get '/concerts', controller: 'concert', action: 'index', as: 'concert_index'
  get '/concerts/:slug', controller: 'concert', action: 'show', as: 'concert_show'
  get '/future-concerts', controller: 'concert', action: 'future_concerts', as: 'future_concerts_index'
  get '/archive-concerts', controller: 'concert', action: 'archive_concerts', as: 'archive_concerts_index'

  get '/news', controller: 'news', action: 'index', as: 'news_index'
  get '/news/:slug', controller: 'news', action: 'show', as: 'news'

  get '/articles', controller: 'article', action: 'index', as: 'article_index'
  get '/articles/:slug', controller: 'article', action: 'show', as: 'article_show'

  get '/bands', controller: 'band', action: 'index', as: 'band_index'
  get '/bands/:slug', controller: 'band', action: 'show', as: 'band_show'

  get '/bases', controller: 'base', action: 'index', as: 'base_index'
  get '/bases/:slug', controller: 'base', action: 'show', as: 'base_show'

  get '/gallery', controller: 'photo_album', action: 'index', as: 'gallery_index'
  get '/gallery/:slug', controller: 'photo_album', action: 'show', as: 'gallery_show'

  get '/videos', controller: 'video', action: 'index', as: 'video_index'
  get '/videos/:slug', controller: 'video', action: 'show', as: 'video_show'

  post '/subscribers', to: 'subscriber#create', as: 'create_subscriber'
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  def index
    bases = RehearsalPoint.order(:name)
    @bases = Kaminari.paginate_array(bases).page(params[:page]).per(5)
  end

  def show
    @base = RehearsalPoint.find_by_slug(params[:slug])
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/views/base/_base.html.slim
.base-container
  .row
    .col-xs-12
      .base-image
        = link_to base_show_path(base.slug), class: 'js-popup-link'
          = image_tag base.base_image.url
      .base-info
        = link_to base_show_path(base.slug), class: 'js-popup-link'
          h2.base-title = base.name
        p Адрес: #{base.address}
        p Контакты: #{base.contacts}

app/views/base/_bases_block.html.slim
= render partial: 'base/base', collection: @bases

= render partial: 'pagination/link_to_next_page', locals: {collection: @bases}

app/views/base/index.html.slim
.container
  .base-wrapper.js-ajax-load
    = render 'base/bases_block'

app/views/base/show.html.slim
.base-detail-page__rep-base
  .base-detail-page__rep-base
    .container
      .row
        .col-md-10.col-md-offset-1
          .base-detail-page.js-page-container
            .base-detail-container
              .row
                .col-xs-12.col-sm-10.col-sm-offset-1
                  .base-detail-page__image-block.base-detail-page__image-block--base
                    = image_tag @base.base_image.url(:detail_page)
                .col-xs-12
                  .base-detail-page__info-block
                    h1.base-info-block__title
                      = @base.name
                .clearfix

              .row
                .col-xs-10.col-xs-offset-1.col-sm-5.col-sm-offset-0
                  .base-detail-page__info-block
                    .base-info-block__info-line
                      span.inline
                        | Адресс:&nbsp;
                      = @base.address
                  .base-detail-page__info-block
                    .base-info-block__info-line
                      span.inline
                        | Контакты:&nbsp;
                      = @base.contacts
                  .base-detail-page__info-block
                    .base-info-block__info-line
                      span.inline
                        | Цены:&nbsp;
                      = @base.price
                  .base-detail-page__text-block.base-detail-page__text-block--min-margin
                    == @base.description

                  .base-repost.base-mobile-repost
                    .base-repost__title
                      | Поделиться:
                    .base-repost__links
                      .base-repost__social-button.base-repost__social-button--vk
                        = render 'svg/vk_icon'
                      = link_to "//facebook.com/share.php?u=kemrockfest.ru#{request.fullpath}&title=#{@base.name}", class: 'base-repost__social-button base-repost__social-button--facebook', target: '_blank'
                        = render 'svg/fb_icon'
                .col-xs-12.col-sm-5.col-sm-offset-1
                  #base-map.base-detail-page__map data-latitude="#{@base.latitude}" data-longitude="#{@base.longitude}" data-hint="#{@base.name}" data-content="#{@base.address}"
              .row
                .col-xs-12
                  .base-detail-page__slider-grid
                    - @base.rehearsal_point_slider_images.each do |slide|
                      = link_to slide.image.url, class: 'base-detail-page__slider-grid-image swipebox js-photo-open', 'rel': 'base', 'title': slide.description
                        = image_tag slide.image.preview.url
            .clearfix