config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', controller: 'home', action: 'index'

  get '/concerts', controller: 'concert', action: 'index', as: 'concert_index'
  get '/concerts/:slug', controller: 'concert', action: 'show', as: 'concert_show'
  get '/future-concerts', controller: 'concert', action: 'future_concerts', as: 'future_concerts_index'
  get '/archive-concerts', controller: 'concert', action: 'archive_concerts', as: 'archive_concerts_index'

  get '/news', controller: 'news', action: 'index', as: 'news_index'
  get '/news/:slug', controller: 'news', action: 'show', as: 'news'

  get '/articles', controller: 'article', action: 'index', as: 'article_index'
  get '/articles/:slug', controller: 'article', action: 'show', as: 'article_show'

  get '/bands', controller: 'band', action: 'index', as: 'band_index'
  get '/bands/:slug', controller: 'band', action: 'show', as: 'band_show'

  get '/bases', controller: 'base', action: 'index', as: 'base_index'
  get '/bases/:slug', controller: 'base', action: 'show', as: 'base_show'

  get '/gallery', controller: 'photo_album', action: 'index', as: 'gallery_index'
  get '/gallery/:slug', controller: 'photo_album', action: 'show', as: 'gallery_show'

  get '/videos', controller: 'video', action: 'index', as: 'video_index'
  get '/videos/:slug', controller: 'video', action: 'show', as: 'video_show'

  post '/subscribers', to: 'subscriber#create', as: 'create_subscriber'
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id          :integer          not null, primary key
#  name        :string
#  slug        :string
#  date_based  :date
#  description :text
#  show        :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  band_image  :string
#

class Band < ApplicationRecord
  extend FriendlyId

  self.table_name = 'bands'

  validates :name, presence: true
  friendly_id :name, use: :slugged

  has_many :band_to_band_members, inverse_of: :band, dependent: :destroy
  has_many :band_members, through: :band_to_band_members

  has_many :band_to_genres, inverse_of: :band, dependent: :destroy
  has_many :genres, through: :band_to_genres

  has_many :concert_to_bands, inverse_of: :band, dependent: :destroy
  has_many :concerts, through: :concert_to_bands

  has_many :band_slider_images, dependent: :delete_all
  accepts_nested_attributes_for :band_slider_images, allow_destroy: true

  mount_uploader :band_image, BandUploader
end

app/controllers/band_controller.rb
class BandController < ApplicationController
  def index
    bands = Band.includes(:band_members, :genres).order(:name)
    bands = bands.where("genres.name like '#{params[:genre]}'").references(:genres).order(:name) unless params[:genre].nil?
    @bands = Kaminari.paginate_array(bands).page(params[:page]).per(5)
  end

  def show
    @band = Band.find_by_slug(params[:slug])
  end

  def genre
    @bands = Band.includes(:band_members).where(name: params[:genre]).order(:name)
  end
end

app/helpers/band_helper.rb
module BandHelper

  def get_genres(genres)
    band_genres = ""
    genres.each_with_index do |genre, index|
      band_genres += "<a href='/bands?genre=#{genre.name}'>#{genre.name}</a>"
        if genres.count - 1 != index
          band_genres += ", "
        end
    end
    band_genres.html_safe
  end

end

app/views/band/_band.html.slim
.band-container
  .row
    .col-xs-12.col-md-6.band-image
      = link_to band_show_path(band.slug), class: 'js-popup-link'
        = image_tag band.band_image.url
    .col-xs-12.col-md-6
      .band-info
        = link_to band_show_path(band.slug), class: 'js-popup-link'
          .band-title = band.name
        - unless band.date_based.nil?
          .band-info-text.date Основана: #{l band.date_based}
        .band-info-text Жанр: #{get_genres(Band.find(band.id).genres)}
        .band-info-text.people Состав:
        ul
          - band.band_members.each do |member|
            li #{member.name} - #{member.music_role.text}

app/views/band/_bands_block.html.slim
= render partial: 'band/band', collection: @bands

= render partial: 'pagination/link_to_next_page', locals: {collection: @bands}

app/views/band/index.html.slim
.container
  .band-wrapper.js-ajax-load
    = render 'band/bands_block'

app/views/band/show.html.slim
.band-detail-wrapper
  .container
    .row
      .col-xs-12.col-md-10.col-md-offset-1
        .base-detail-page.js-page-container.base-detail-page--band
          .base-detail-container
            .row
              .col-xs-12
                .base-detail-page__info-block.no-margin
                  h1.base-info-block__title
                    = @band.name
              .col-xs-12.col-sm-10.col-sm-offset-1
                .base-detail-page__image-block.band-detail-image.band-detail-image--band
                  = image_tag @band.band_image.url(:detail_page)
              .col-xs-10.col-xs-offset-1.col-sm-7.col-sm-offset-1
                .base-detail-page__info-block
                  - @band.date_based.nil?
                    .base-info-block__info-line
                      span.inline
                        | Основана:&nbsp;
                      = "#{l @band.date_based }"
                  .base-info-block__info-line
                    span.genre-list-title
                      | Жанр:&nbsp;
                    .genre-list
                      = get_genres @band.genres
                  - if @band.band_members.count > 0
                    .base-info-block__info-line
                      span.mb-5
                        | Cостав:&nbsp;
                      ul.band-list
                        - @band.band_members.each do |member|
                          li = "#{member.name} - #{member.music_role.text}"
                  .band-repost-wrapper
                    .base-repost
                      .base-repost__title
                        | Поделиться:
                      .base-repost__links
                        = link_to '', class: 'base-repost__social-button base-repost__social-button--vk'
                          = render 'svg/vk_icon'
                        = link_to "//facebook.com/share.php?u=kemrockfest.ru#{request.fullpath}&title=#{@band.name}", class: 'base-repost__social-button base-repost__social-button--facebook', target: '_blank'
                          = render 'svg/fb_icon'
              .clearfix
            - if @band.band_slider_images.count > 0
              .row
                .col-xs-8.col-xs-offset-2.col-sm-10.col-sm-offset-1
                  .base-detail-page__slider id="band-slider"
                    - @band.band_slider_images.each do |slide|
                      = link_to slide.image.url, class: "base-detail-page__slide swipebox js-photo-open", "rel": "band", "title": slide.description
                        = image_tag slide.image.url
              .clearfix
            .row
              .col-sm-10.col-sm-offset-1
                .base-detail-page__text-block
                  == @band.description
              .clearfix
        .clearfix