config/routes.rb
# == Route Map
#

Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', controller: 'home', action: 'index'

  get '/concerts', controller: 'concert', action: 'index', as: 'concert_index'
  get '/concerts/:slug', controller: 'concert', action: 'show', as: 'concert_show'
  get '/future-concerts', controller: 'concert', action: 'future_concerts', as: 'future_concerts_index'
  get '/archive-concerts', controller: 'concert', action: 'archive_concerts', as: 'archive_concerts_index'

  get '/news', controller: 'news', action: 'index', as: 'news_index'
  get '/news/:slug', controller: 'news', action: 'show', as: 'news'

  get '/articles', controller: 'article', action: 'index', as: 'article_index'
  get '/articles/:slug', controller: 'article', action: 'show', as: 'article_show'

  get '/bands', controller: 'band', action: 'index', as: 'band_index'
  get '/bands/:slug', controller: 'band', action: 'show', as: 'band_show'

  get '/bases', controller: 'base', action: 'index', as: 'base_index'
  get '/bases/:slug', controller: 'base', action: 'show', as: 'base_show'

  get '/gallery', controller: 'photo_album', action: 'index', as: 'gallery_index'
  get '/gallery/:slug', controller: 'photo_album', action: 'show', as: 'gallery_show'

  get '/videos', controller: 'video', action: 'index', as: 'video_index'
  get '/videos/:slug', controller: 'video', action: 'show', as: 'video_show'

  post '/subscribers', to: 'subscriber#create', as: 'create_subscriber'
end

app/controllers/home_controller.rb
require 'date'

class HomeController < ApplicationController
  def index
    @concerts = Concert.includes(:bands).includes(:photo_album).where("date_start >= now()").order(:date_start).first(7)
    @news = News.order(date_publication: :desc).first(6)
    @photo_albums = Concert.includes(:photo_album).where.not(:photo_albums => { id: nil }).where("date_start >= now()").order(:date_start).first(5)
    @last_concert_time = get_milliseconds @concerts[0].date_start unless @concerts[0].nil?
    @videos = Video.order(date_publication: :desc).first(5)
  end

  private
    def get_milliseconds(date)
      (date.to_f * 1000).to_i
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_concert.html.slim
.base-home-wrapper
  .concerts-content.par id="concerts"
    .row
      .col-xs-12.col-md-3
        h1.block-title Ожидаются

    .poster-wrapper-mobile
      - @concerts.each do |concert|
        .row
          .poster-mobile-content
            .col-xs-6
              = link_to concert_show_path(concert.slug), class: 'js-popup-link'
                = image_tag concert.poster_image.try(:url)
            .col-xs-6
              .poster-mobile-info-content
                .poster-mobile-title #{concert.name}
                .poster-mobile-text #{concert.place}
                .poster-mobile-date #{l concert.date_start.to_date} #{concert.date_start.hour}:#{concert.date_start.min.to_s.rjust(2, '0')}
                - concert.bands.each do |band|
                  .poster-mobile-band #{band.name}

                .poster-mobile-price Вход: #{concert.ticket_price}р.

    .posters-wrapper
      .row
        - unless @concerts[0].nil?
          .col-md-4.col-md-offset-1
            .poster-big
              = link_to concert_show_path(@concerts[0].slug), class: 'js-popup-link'
                = image_tag @concerts[0].poster_image.try(:url)
                .index-poster-info-big-wrapper
                  .index-poster-info-big-content
                    .poster-title--big #{@concerts[0].name}
                    .poster-medium-text--big #{@concerts[0].place}
                    .poster-medium-text--big #{l @concerts[0].date_start.to_date} #{@concerts[0].date_start.hour}:#{@concerts[0].date_start.min}

                    - @concerts[0].bands.each do |band|
                      .poster-band--big #{band.name}

                    .poster-price--big Вход: #{@concerts[0].ticket_price}р.

        .col-md-7
          - for i in 1..@concerts.count - 1
            - unless @concerts[i].nil?
              .poster-small
                = link_to concert_show_path(@concerts[i].slug), class: 'js-popup-link'
                  = image_tag @concerts[i].poster_image.try(:url)
                  .index-poster-info-small
                    .poster-title--small #{@concerts[i].name}
                    .poster-medium-text--small #{@concerts[i].place}
                    .poster-medium-text--small #{l @concerts[i].date_start.to_date} #{@concerts[i].date_start.hour}:#{@concerts[i].date_start.min}
                    - @concerts[i].bands.each do |band|
                      .poster-band--small #{band.name}

                    .poster-price--small Вход: #{@concerts[i].ticket_price}р.

app/views/home/_counter.html.slim
.row
  .col-xs-12.col-sm-12.col-md-12.col-lg-12
    .counter.par id="counter"
      h1.counter-header
        = @concerts[0].name
      .counter-block
        .counter-number
          .counter-number__number id="concert_days"
          .counter-number__title id="concert_days_title"
        .counter-colon =":"
        .counter-number
          .counter-number__number id="concert_hours"
          .counter-number__title id="concert_hours_title"
        .counter-colon =":"
        .counter-number
          .counter-number__number id="concert_minutes"
          .counter-number__title id="concert_minutes_title"
        .counter-colon =":"
        .counter-number
          .counter-number__number id="concert_seconds"
          .counter-number__title id="concert_seconds_title" СЕКУНД

app/views/home/_news.html.slim
.base-home-wrapper
  .articles-content.par id="news"
    .col-sm-12
      h1.block-title Новости

    .articles-mobile-wrapper
      .row
        - for i in 0..5
          - unless @news[i].nil?
            .col-xs-12.col-sm-6
              .article-mobile-content
                = link_to news_path(@news[i].slug), class: 'js-popup-link'
                  = image_tag @news[i].news_image.try(:url)
                  .article-mobile-text
                    .article-mobile-text__date #{@news[i].date_publication.strftime("%d.%m.%Y")}
                    .article-mobile-text__title #{@news[i].name}

    .articles
      .row
        .col-md-5.col-md-offset-1
          .article-big
            = link_to news_path(@news[0].slug), class: 'js-popup-link'
              = image_tag @news[0].news_image.try(:url)
              .article-big-text
                .article-big-text__date #{@news[0].date_publication.strftime("%d.%m.%Y")}
                .article-big-text__title #{@news[0].name}
        .col-md-6
          - for i in 1..4
            - unless @news[i].nil?
              .article-small
                = link_to news_path(@news[i].slug), class: 'js-popup-link'
                  = image_tag @news[i].news_image.try(:url)
                  .article-small-info
                    .article-small-text__date #{@news[i].date_publication.strftime("%d.%m.%Y")}
                    .article-small-text__title #{@news[i].name}

app/views/home/_photos.html.slim
.base-home-wrapper
  .articles-content.par id="photos"
    .col-sm-12
      h1.block-title Фотоотчеты

    .articles-mobile-wrapper
      .row
        - @photo_albums.each do |album|
          .col-xs-12.col-sm-6
            .article-mobile-content
              = link_to gallery_show_path(album.photo_album.slug)
                = image_tag album.photo_album.preview_image.try(:url)
                .article-mobile-text
                  .article-mobile-text__date #{album.date_start.strftime("%d.%m.%Y")}
                  .article-mobile-text__title #{album.photo_album.name}


    .articles
      .row
        .col-md-5.col-md-offset-1
          .article-big
            = link_to gallery_show_path(@photo_albums[0].photo_album.slug)
              = image_tag @photo_albums[0].photo_album.preview_image.try(:url)
              .article-big-text
                .article-big-text__date #{@photo_albums[0].date_start.strftime("%d.%m.%Y")}
                .article-big-text__title #{@photo_albums[0].photo_album.name}

        .col-md-6
          - for i in 1..4
            - unless @photo_albums[i].nil?
              .article-small
                = link_to gallery_show_path(@photo_albums[i].photo_album.slug)
                  = image_tag @photo_albums[i].photo_album.preview_image.try(:url)
                  .article-small-info
                    .article-small-text__date #{@photo_albums[i].date_start.strftime("%d.%m.%Y")}
                    .article-small-text__title #{@photo_albums[i].photo_album.name}

app/views/home/_videos.html.slim
.base-home-wrapper
  .articles-content.par id="videos"
    .col-sm-12
      h1.block-title Видео

    .articles-mobile-wrapper
      .row
        - @videos.each do |video|
          .col-xs-12.col-sm-6
            .article-mobile-content
              = link_to video_show_path(video.slug), class: 'js-popup-link'
                = image_tag video.preview_image.try(:url)
                .article-mobile-text
                  .article-mobile-text__date 22.05.2017
                  .article-mobile-text__title Rock Festival Eclipse

    .articles
      .row
        .col-md-5.col-md-offset-1
          .article-big
            = link_to video_show_path(@videos[0].slug), class: 'js-popup-link'
              = image_tag @videos[0].preview_image.try(:url)
              .article-big-text
                .article-big-text__date #{@videos[0].date_publication.strftime("%d.%m.%Y")}
                .article-big-text__title = @videos[0].name
        .col-md-6
          - for i in 1..@videos.length-1
            - unless @videos[i].nil?
              .article-small
                = link_to video_show_path(@videos[i].slug), class: 'js-popup-link'
                  = image_tag @videos[i].preview_image.try(:url)
                  .article-small-info
                    .article-small-text__date #{@videos[i].date_publication.strftime("%d.%m.%Y")}
                    .article-small-text__title = @videos[i].name

app/views/home/index.html.slim
.page-nav-dots-wrapper
  = link_to '', '#counter', class: "nav-dot active"
  = link_to '', '#concerts', class: "nav-dot"
  = link_to '', '#photos', class: "nav-dot"
  = link_to '', '#news', class: "nav-dot"
  = link_to '', '#videos', class: "nav-dot"

.container
  - if @concerts.count > 0
    = render 'home/counter'
    = render 'home/concert'
  - if @photo_albums.count > 0
    = render 'home/photos'
  - if @news.count > 0
    = render 'home/news'
  - if @videos.count > 0
    = render partial: 'home/videos'

  = content_tag :div, id: 'last_concert_time', class: "hidden-block", data: {last_concert_time: @last_concert_time} do

app/views/home/videos.html.slim
.base-home-wrapper
  .container
    .row
      .videos-container
        .col-md-4.video-block
          .title-block
            h4 22.10.2016г.
            h4 Rock Festival Eclipse

          = link_to '#'
            .video-poster
              = image_tag 'dev_video.jpg'
              .bands
                p Around the World in 80 days
                p Port Royal
                p Water, Please
                p А-Симметрия
                p Jahksinia

        .col-md-4.video-block
          .title-block
            h4 22.10.2016г.
            h4 Rock Festival Eclipse

          = link_to '#'
            .video-poster
              = image_tag 'dev_video.jpg'
              .bands
                p Around the World in 80 days
                p Port Royal
                p Water, Please
                p А-Симметрия
                p Jahksinia

        .col-md-4.video-block
          .title-block
            h4 22.10.2016г.
            h4 Rock Festival Eclipse

          = link_to '#'
          .video-poster
            = image_tag 'dev_video.jpg'
            .bands
              p Around the World in 80 days
              p Port Royal
              p Water, Please
              p А-Симметрия
              p Jahksinia

  .container
    .separator

  .container
    .row
      .videos-container
        .col-md-4.video-block
          .title-block
            h4 22.10.2016г.
            h4 Rock Festival Eclipse

          = link_to '#'
          .video-poster
            = image_tag 'dev_video.jpg'
            .bands
              p Around the World in 80 days
              p Port Royal
              p Water, Please
              p А-Симметрия
              p Jahksinia

        .col-md-4.video-block
          .title-block
            h4 22.10.2016г.
            h4 Rock Festival Eclipse

          = link_to '#'
          .video-poster
            = image_tag 'dev_video.jpg'
            .bands
              p Around the World in 80 days
              p Port Royal
              p Water, Please
              p А-Симметрия
              p Jahksinia

        .col-md-4.video-block
          .title-block
            h4 22.10.2016г.
            h4 Rock Festival Eclipse

          = link_to '#'
          .video-poster
            = image_tag 'dev_video.jpg'
            .bands
              p Around the World in 80 days
              p Port Royal
              p Water, Please
              p А-Симметрия
              p Jahksinia